//! Black Box: JSON schemes ("Flandre Dark" / "Flandre Light") in its schemes directory and the
//! `theme-dark` / `theme-light` / `pretty` settings, for the host package and the Flatpak.

use crate::colors::{Palette, hex};
use crate::util;
use anyhow::Result;
use gio::prelude::*;
use std::path::PathBuf;

const SCHEMA: &str = "com.raggesilver.BlackBox";
const FLATPAK_ID: &str = "com.raggesilver.BlackBox";

pub fn scheme_json(p: &Palette) -> String {
    let name = if p.dark { "Flandre Dark" } else { "Flandre Light" };
    let palette: Vec<String> = p.ansi.iter().map(|c| format!("        \"{}\"", hex(*c))).collect();
    format!(
        "{{\n    \"name\": \"{name}\",\n    \"comment\": \"Generated by Flandre from the wallpaper\",\n    \"use-theme-colors\": false,\n    \"foreground-color\": \"{fg}\",\n    \"background-color\": \"{bg}\",\n    \"cursor-color\": \"{cursor}\",\n    \"palette\": [\n{palette}\n    ]\n}}\n",
        fg = hex(p.term_fg),
        bg = hex(p.term_bg),
        cursor = hex(p.cursor),
        palette = palette.join(",\n"),
    )
}

pub struct BlackBoxResult {
    pub files: Vec<PathBuf>,
}

pub fn apply(dark: &Palette, light: &Palette) -> Result<BlackBoxResult> {
    let mut files = Vec::new();
    let mut dirs = Vec::new();
    let host = util::exists_in_path("blackbox") || util::schema_exists(SCHEMA);
    if host {
        dirs.push((util::data_home().join("blackbox/schemes"), false));
    }
    if util::flatpak_app_installed(FLATPAK_ID) {
        dirs.push((
            util::home()
                .join(".var/app")
                .join(FLATPAK_ID)
                .join("data/blackbox/schemes"),
            true,
        ));
    }
    for (dir, flatpak) in dirs {
        for p in [dark, light] {
            let f = dir.join(if p.dark {
                "flandre-dark.json"
            } else {
                "flandre-light.json"
            });
            util::write_atomic(&f, scheme_json(p).as_bytes())?;
            files.push(f);
        }
        if flatpak {
            for (k, v) in [
                ("theme-dark", "'Flandre Dark'"),
                ("theme-light", "'Flandre Light'"),
                ("pretty", "true"),
            ] {
                let _ = util::run(
                    "flatpak",
                    &["run", "--command=gsettings", FLATPAK_ID, "set", SCHEMA, k, v],
                );
            }
        } else if let Some(s) = util::settings(SCHEMA) {
            let _ = s.set_string("theme-dark", "Flandre Dark");
            let _ = s.set_string("theme-light", "Flandre Light");
            let _ = s.set_boolean("pretty", true);
            gio::Settings::sync();
        }
    }
    Ok(BlackBoxResult { files })
}
