//! libadwaita (GTK 4) and adw-gtk3 (GTK 3): `~/.config/gtk-{3,4}.0/gtk.css`.

use crate::colors::{Palette, hex};
use crate::util;
use anyhow::Result;
use std::fmt::Write;

pub const MARKER: &str = "/* Generated by Flandre - edits will be overwritten */";

/// Every named colour as (name, value) pairs, in libadwaita's naming.
pub fn named_colors(p: &Palette) -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = Vec::with_capacity(100);
    let mut def = |name: &str, value: String| out.push((name.to_string(), value));
    let h = hex;
    def("accent_color", h(p.primary));
    def("accent_bg_color", h(p.primary));
    def("accent_fg_color", h(p.on_primary));
    def("destructive_color", h(p.error));
    def(
        "destructive_bg_color",
        h(if p.dark { p.error_container } else { p.error }),
    );
    def(
        "destructive_fg_color",
        h(if p.dark { p.on_error_container } else { p.on_error }),
    );
    def("success_color", h(p.success));
    def("success_bg_color", h(p.success_bg));
    def("success_fg_color", "#ffffff".into());
    def("warning_color", h(p.warning));
    def("warning_bg_color", h(p.warning_bg));
    def("warning_fg_color", "rgba(0, 0, 0, 0.8)".into());
    def("error_color", h(p.error));
    def("error_bg_color", h(if p.dark { p.error_container } else { p.error }));
    def(
        "error_fg_color",
        h(if p.dark { p.on_error_container } else { p.on_error }),
    );
    def("window_bg_color", h(p.window_bg));
    def("window_fg_color", h(p.on_surface));
    def("view_bg_color", h(p.view_bg));
    def("view_fg_color", h(p.on_surface));
    def("headerbar_bg_color", h(p.headerbar_bg));
    def("headerbar_fg_color", h(p.on_surface));
    def("headerbar_border_color", h(p.on_surface));
    def("headerbar_backdrop_color", "@window_bg_color".into());
    def(
        "headerbar_shade_color",
        if p.dark {
            "rgba(0, 0, 0, 0.36)".into()
        } else {
            "rgba(0, 0, 0, 0.12)".into()
        },
    );
    def(
        "headerbar_darker_shade_color",
        if p.dark {
            "rgba(0, 0, 0, 0.9)".into()
        } else {
            "rgba(0, 0, 0, 0.12)".into()
        },
    );
    def("card_bg_color", h(p.card_bg));
    def("card_fg_color", h(p.on_surface));
    def(
        "card_shade_color",
        if p.dark {
            "rgba(0, 0, 0, 0.36)".into()
        } else {
            "rgba(0, 0, 0, 0.07)".into()
        },
    );
    def("dialog_bg_color", h(p.dialog_bg));
    def("dialog_fg_color", h(p.on_surface));
    def("popover_bg_color", h(p.popover_bg));
    def("popover_fg_color", h(p.on_surface));
    def(
        "popover_shade_color",
        if p.dark {
            "rgba(0, 0, 0, 0.36)".into()
        } else {
            "rgba(0, 0, 0, 0.07)".into()
        },
    );
    def(
        "shade_color",
        if p.dark {
            "rgba(0, 0, 0, 0.36)".into()
        } else {
            "rgba(0, 0, 0, 0.07)".into()
        },
    );
    def(
        "scrollbar_outline_color",
        if p.dark {
            "rgba(0, 0, 0, 0.5)".into()
        } else {
            "#ffffff".into()
        },
    );
    def("thumbnail_bg_color", h(p.thumbnail_bg));
    def("thumbnail_fg_color", h(p.on_surface));
    def("sidebar_bg_color", h(p.sidebar_bg));
    def("sidebar_fg_color", h(p.on_surface));
    def(
        "sidebar_border_color",
        if p.dark {
            "rgba(0, 0, 0, 0.36)".into()
        } else {
            "rgba(0, 0, 0, 0.07)".into()
        },
    );
    def("sidebar_backdrop_color", h(p.secondary_sidebar_bg));
    def(
        "sidebar_shade_color",
        if p.dark {
            "rgba(0, 0, 0, 0.25)".into()
        } else {
            "rgba(0, 0, 0, 0.07)".into()
        },
    );
    def("secondary_sidebar_bg_color", h(p.secondary_sidebar_bg));
    def("secondary_sidebar_fg_color", h(p.on_surface));
    def(
        "secondary_sidebar_border_color",
        if p.dark {
            "rgba(0, 0, 0, 0.36)".into()
        } else {
            "rgba(0, 0, 0, 0.07)".into()
        },
    );
    def("secondary_sidebar_backdrop_color", h(p.window_bg));
    def(
        "secondary_sidebar_shade_color",
        if p.dark {
            "rgba(0, 0, 0, 0.25)".into()
        } else {
            "rgba(0, 0, 0, 0.07)".into()
        },
    );
    def("overview_bg_color", h(p.surface_container_low));
    def("overview_fg_color", h(p.on_surface));
    def(
        "active_toggle_bg_color",
        if p.dark {
            "rgba(255, 255, 255, 0.2)".into()
        } else {
            "#ffffff".into()
        },
    );
    def("active_toggle_fg_color", h(p.on_surface));
    def(
        "borders",
        if p.dark {
            "rgba(255, 255, 255, 0.15)".into()
        } else {
            "rgba(0, 0, 0, 0.15)".into()
        },
    );
    let rows: [(&str, &[material_colors::color::Argb; 5]); 9] = [
        ("blue", &p.blue),
        ("green", &p.green),
        ("yellow", &p.yellow),
        ("orange", &p.orange),
        ("red", &p.red),
        ("purple", &p.purple),
        ("brown", &p.brown),
        ("light", &p.light),
        ("dark", &p.darks),
    ];
    for (name, row) in rows {
        for (i, c) in row.iter().enumerate() {
            def(&format!("{name}_{}", i + 1), h(*c));
        }
    }
    // Material extras for apps that opt in.
    def("flandre_primary", h(p.primary));
    def("flandre_primary_container", h(p.primary_container));
    def("flandre_on_primary_container", h(p.on_primary_container));
    def("flandre_secondary", h(p.secondary));
    def("flandre_secondary_container", h(p.secondary_container));
    def("flandre_tertiary", h(p.tertiary));
    def("flandre_tertiary_container", h(p.tertiary_container));
    def("flandre_surface", h(p.surface));
    def("flandre_surface_container_high", h(p.surface_container_high));
    def("flandre_outline", h(p.outline));
    out
}

/// The `@define-color` block (GTK 3 and older libadwaita) for one mode.
pub fn define_block(p: &Palette) -> String {
    let mut s = String::with_capacity(5000);
    for (name, value) in named_colors(p) {
        let _ = writeln!(s, "@define-color {name} {value};");
    }
    s
}

/// The same colours as CSS variables on `:root` (libadwaita 1.6+), so a running app follows a
/// light/dark switch without restarting.
pub fn vars_block(p: &Palette, indent: &str) -> String {
    let mut s = String::with_capacity(5000);
    let _ = writeln!(s, "{indent}:root {{");
    for (name, value) in named_colors(p) {
        let value = match value.strip_prefix('@') {
            Some(name) => format!("var(--{})", name.replace('_', "-")),
            None => value,
        };
        let _ = writeln!(s, "{indent}  --{}: {value};", name.replace('_', "-"));
    }
    let _ = writeln!(s, "{indent}}}");
    s
}

/// Rules that push the wash further than named colours reach.
pub fn rules(p: &Palette) -> String {
    let mut s = String::new();

    // Named colours reach everything libadwaita exposes; these rules push the wash a bit further
    // (selection, tabs, and the parts that only use the neutral greys).
    s.push_str(&format!(
        "\n\
selection, *:selected {{ background-color: alpha(@accent_bg_color, {sel}); }}\n\
.navigation-sidebar > row:selected, listview > row:selected, .navigation-sidebar > row:selected:hover {{ background-color: alpha(@accent_bg_color, {sel2}); }}\n\
tabbar tab:checked, tabbar tab:checked:hover {{ background-color: alpha(@accent_bg_color, 0.18); }}\n\
switch:checked {{ background-color: @accent_bg_color; }}\n\
progressbar > trough > progress, scale > trough > highlight {{ background-color: @accent_bg_color; }}\n\
.osd, .osd.toast, toast {{ background-color: alpha({popover}, 0.92); color: @popover_fg_color; }}\n\
entry:focus-within, textview:focus-within {{ outline-color: alpha(@accent_bg_color, 0.55); }}\n",
        sel = if p.dark { "0.35" } else { "0.28" },
        sel2 = if p.dark { "0.24" } else { "0.18" },
        popover = hex(p.popover_bg),
    ));
    s
}

/// GTK 4: current mode as `@define-color` plus both modes as variables under a media query.
pub fn css_gtk4(current: &Palette, dark: &Palette, light: &Palette) -> String {
    let mut s = String::with_capacity(16000);
    let _ = writeln!(s, "{MARKER}");
    s.push_str(&define_block(current));
    s.push_str(&vars_block(light, ""));
    s.push_str("@media (prefers-color-scheme: dark) {\n");
    s.push_str(&vars_block(dark, "  "));
    s.push_str("}\n");
    s.push_str(&rules(current));
    s
}

/// GTK 3 (adw-gtk3): no variables, no media queries; the current mode only.
pub fn css_gtk3(current: &Palette) -> String {
    format!("{MARKER}\n{}{}", define_block(current), rules(current))
}

pub fn apply(current: &Palette, dark: &Palette, light: &Palette) -> Result<Vec<String>> {
    let mut written = Vec::new();
    for dir in ["gtk-4.0", "gtk-3.0"] {
        let text = if dir == "gtk-4.0" {
            css_gtk4(current, dark, light)
        } else {
            css_gtk3(current)
        };
        let path = util::config_home().join(dir).join("gtk.css");
        if path.exists() {
            let old = std::fs::read_to_string(&path).unwrap_or_default();
            if !old.contains(MARKER) && !old.contains("@define-color accent_color") && !old.trim().is_empty() {
                // Someone else's hand-written CSS: keep it after ours.
                let backup = path.with_extension("css.pre-flandre");
                if !backup.exists() {
                    std::fs::copy(&path, &backup)?;
                }
                let merged = format!("{text}\n/* --- previous gtk.css kept below --- */\n{old}");
                util::write_atomic(&path, merged.as_bytes())?;
                written.push(path.display().to_string());
                continue;
            }
        }
        util::write_atomic(&path, text.as_bytes())?;
        written.push(path.display().to_string());
    }
    Ok(written)
}
