//! Any VTE/xterm-compatible terminal already open (Console included, which has no palette API on
//! older versions): OSC 4/10/11/12 sequences broadcast to every pty, plus files under
//! `~/.cache/flandre/` for shell rc snippets and user scripts.

use crate::colors::{Palette, hex};
use crate::util;
use anyhow::Result;
use std::fmt::Write as _;
use std::io::Write;
use std::path::PathBuf;

pub fn sequences(p: &Palette) -> String {
    let mut s = String::new();
    for (i, c) in p.ansi.iter().enumerate() {
        let _ = write!(s, "\x1b]4;{i};{}\x1b\\", hex(*c));
    }
    let _ = write!(s, "\x1b]10;{}\x1b\\", hex(p.term_fg));
    let _ = write!(s, "\x1b]11;{}\x1b\\", hex(p.term_bg));
    let _ = write!(s, "\x1b]12;{}\x1b\\", hex(p.cursor));
    let _ = write!(s, "\x1b]17;{}\x1b\\", hex(p.primary_container));
    let _ = write!(s, "\x1b]19;{}\x1b\\", hex(p.on_primary_container));
    s
}

pub fn colors_json(p: &Palette) -> String {
    let mut s = String::from("{\n");
    let _ = writeln!(s, "  \"wallpaper_source\": \"{}\",", hex(p.source));
    let _ = writeln!(s, "  \"mode\": \"{}\",", if p.dark { "dark" } else { "light" });
    let fields = [
        ("primary", p.primary),
        ("on_primary", p.on_primary),
        ("primary_container", p.primary_container),
        ("on_primary_container", p.on_primary_container),
        ("secondary", p.secondary),
        ("secondary_container", p.secondary_container),
        ("tertiary", p.tertiary),
        ("tertiary_container", p.tertiary_container),
        ("error", p.error),
        ("surface", p.surface),
        ("surface_container", p.surface_container),
        ("surface_container_high", p.surface_container_high),
        ("on_surface", p.on_surface),
        ("outline", p.outline),
        ("window_bg", p.window_bg),
        ("view_bg", p.view_bg),
        ("headerbar_bg", p.headerbar_bg),
        ("sidebar_bg", p.sidebar_bg),
        ("popover_bg", p.popover_bg),
        ("term_bg", p.term_bg),
        ("term_fg", p.term_fg),
        ("cursor", p.cursor),
    ];
    for (k, v) in fields {
        let _ = writeln!(s, "  \"{k}\": \"{}\",", hex(v));
    }
    let ansi: Vec<String> = p.ansi.iter().map(|c| format!("\"{}\"", hex(*c))).collect();
    let _ = writeln!(s, "  \"ansi\": [{}]", ansi.join(", "));
    s.push_str("}\n");
    s
}

pub fn colors_sh(p: &Palette) -> String {
    let mut s = String::from("# Generated by Flandre\n");
    let _ = writeln!(s, "FLANDRE_MODE='{}'", if p.dark { "dark" } else { "light" });
    let _ = writeln!(s, "FLANDRE_PRIMARY='{}'", hex(p.primary));
    let _ = writeln!(s, "FLANDRE_ON_PRIMARY='{}'", hex(p.on_primary));
    let _ = writeln!(s, "FLANDRE_SURFACE='{}'", hex(p.surface));
    let _ = writeln!(s, "FLANDRE_ON_SURFACE='{}'", hex(p.on_surface));
    let _ = writeln!(s, "FLANDRE_HEADERBAR='{}'", hex(p.headerbar_bg));
    let _ = writeln!(s, "FLANDRE_TERM_BG='{}'", hex(p.term_bg));
    let _ = writeln!(s, "FLANDRE_TERM_FG='{}'", hex(p.term_fg));
    for (i, c) in p.ansi.iter().enumerate() {
        let _ = writeln!(s, "FLANDRE_COLOR{i}='{}'", hex(*c));
    }
    s
}

pub struct OscResult {
    pub files: Vec<PathBuf>,
    pub ptys: usize,
}

pub fn apply(p: &Palette, broadcast: bool) -> Result<OscResult> {
    let dir = util::flandre_cache_dir();
    let seq = sequences(p);
    let files = vec![
        (dir.join("sequences"), seq.clone()),
        (dir.join("colors.json"), colors_json(p)),
        (dir.join("colors.sh"), colors_sh(p)),
    ];
    let mut written = Vec::new();
    for (f, content) in files {
        util::write_atomic(&f, content.as_bytes())?;
        written.push(f);
    }
    let mut ptys = 0;
    if broadcast && let Ok(rd) = std::fs::read_dir("/dev/pts") {
        for e in rd.flatten() {
            let name = e.file_name();
            if name.to_string_lossy().chars().all(|c| c.is_ascii_digit())
                && let Ok(mut f) = std::fs::OpenOptions::new().write(true).open(e.path())
                && f.write_all(seq.as_bytes()).is_ok()
            {
                ptys += 1;
            }
        }
    }
    Ok(OscResult { files: written, ptys })
}
