//! Ptyxis: a native `.palette` file (light + dark, titlebar included) selected in every profile,
//! for the host package and the Flatpak.

use crate::colors::{Palette, hex};
use crate::util;
use anyhow::Result;
use gio::prelude::*;
use std::fmt::Write;
use std::path::PathBuf;

pub const PALETTE_ID: &str = "flandre";
const FLATPAK_ID: &str = "app.devsuite.Ptyxis";

fn group(out: &mut String, name: &str, p: &Palette) {
    let _ = writeln!(out, "\n[{name}]");
    let _ = writeln!(out, "Foreground={}", hex(p.term_fg));
    let _ = writeln!(out, "Background={}", hex(p.term_bg));
    let _ = writeln!(out, "TitlebarBackground={}", hex(p.headerbar_bg));
    let _ = writeln!(out, "TitlebarForeground={}", hex(p.on_surface));
    let _ = writeln!(out, "Cursor={}", hex(p.cursor));
    let _ = writeln!(out, "SuperuserForeground={}", hex(p.term_fg));
    let _ = writeln!(out, "SuperuserBackground={}", hex(p.error_container));
    let _ = writeln!(out, "RemoteForeground={}", hex(p.term_fg));
    let _ = writeln!(out, "RemoteBackground={}", hex(p.tertiary_container));
    for (i, c) in p.ansi.iter().enumerate() {
        let _ = writeln!(out, "Color{i}={}", hex(*c));
    }
}

pub fn palette_file(dark: &Palette, light: &Palette) -> String {
    let mut s = String::from("# Generated by Flandre from the wallpaper\n\n[Palette]\nName=Flandre\n");
    group(&mut s, "Light", light);
    group(&mut s, "Dark", dark);
    s
}

pub struct PtyxisResult {
    pub files: Vec<PathBuf>,
    pub profiles: usize,
}

pub fn apply(dark: &Palette, light: &Palette) -> Result<PtyxisResult> {
    let text = palette_file(dark, light);
    let mut files = Vec::new();
    let mut profiles = 0;

    let host = util::exists_in_path("ptyxis") || util::schema_exists("org.gnome.Ptyxis");
    if host {
        let f = util::data_home()
            .join("org.gnome.Ptyxis/palettes")
            .join(format!("{PALETTE_ID}.palette"));
        util::write_atomic(&f, text.as_bytes())?;
        files.push(f);
        profiles += select_host()?;
    }
    if util::flatpak_app_installed(FLATPAK_ID) {
        let f = util::home()
            .join(".var/app")
            .join(FLATPAK_ID)
            .join("data/org.gnome.Ptyxis/palettes")
            .join(format!("{PALETTE_ID}.palette"));
        util::write_atomic(&f, text.as_bytes())?;
        files.push(f);
        profiles += select_flatpak();
    }
    Ok(PtyxisResult { files, profiles })
}

fn select_host() -> Result<usize> {
    let Some(s) = util::settings("org.gnome.Ptyxis") else {
        return Ok(0);
    };
    let mut uuids: Vec<String> = s.strv("profile-uuids").iter().map(|g| g.to_string()).collect();
    let def = s.string("default-profile-uuid").to_string();
    if !def.is_empty() && !uuids.contains(&def) {
        uuids.push(def);
    }
    let mut n = 0;
    for u in uuids {
        if let Some(prof) = util::settings_at("org.gnome.Ptyxis.Profile", &format!("/org/gnome/Ptyxis/Profiles/{u}/"))
            && prof.set_string("palette", PALETTE_ID).is_ok()
        {
            n += 1;
        }
    }
    gio::Settings::sync();
    Ok(n)
}

fn select_flatpak() -> usize {
    let gs = |args: &[&str]| {
        let mut full = vec!["run", "--command=gsettings", FLATPAK_ID];
        full.extend_from_slice(args);
        util::run("flatpak", &full).ok()
    };
    let Some(list) = gs(&["get", "org.gnome.Ptyxis", "profile-uuids"]) else {
        return 0;
    };
    let mut n = 0;
    for u in list.trim_matches(|c| c == '[' || c == ']').split(',') {
        let u = u.trim().trim_matches('\'');
        if u.is_empty() {
            continue;
        }
        let path = format!("org.gnome.Ptyxis.Profile:/org/gnome/Ptyxis/Profiles/{u}/");
        if gs(&["set", &path, "palette", PALETTE_ID]).is_some() {
            n += 1;
        }
    }
    n
}
